export type LandingLanguage = "en" | "es";

export const landingCopy = {
  en: {
    navHow: "How It Works",
    navGames: "Games",
    navMining: "Mining",
    navRewards: "Rewards",
    login: "Log In",
    getStarted: "Get Started",
    heroA: "Earn Zyxes.",
    heroB: "Play, claim and grow.",
    heroSub:
      "Claim internal rewards, play simple games, build virtual mining power and explore the planned conversion flow.",
    ctaStart: "Start Earning",
    ctaExplore: "Explore Fauzet",
    heroDisclaimer:
      "ZYXE is an internal utility and reward unit. Rewards are variable, based on valid activity, and may be subject to verification, limits and anti-fraud controls.",
    preview: "Product preview",
    pvClaim: "Claim ZYXEs",
    pvWallet: "Wallet balance",
    pvReady: "Ready!",
    pvNextClaim: "Next claim in",
    pvMiningPower: "Mining power",
    pvActiveMiners: "Active miners",
    pvEfficiency: "Efficiency",
    pvPoolShare: "Pool share (daily)",
    pvViewDetails: "View details",
    howTitle: "How Fauzet works",
    howSub: "Four steps from zero to eligible rewards.",
    earnTitle: "Ways to earn",
    earnSub:
      "Stack ZYXEs across multiple activities. Every reward is validated before it settles.",
    zxTag: "INTERNAL UTILITY UNIT",
    zxTitle: "What can you do with ZYXEs?",
    zxDesc:
      "ZYXE is the reward and utility unit of the Fauzet ecosystem. Earn it through validated activity and spend it inside the platform to grow faster.",
    zxLegal:
      "ZYXE begins as an internal unit with no public price or automatic convertibility. It does not represent equity, debt or a promise of profitability.",
    mnTag: "VIRTUAL MINING",
    mnTitle: "Build mining power. Share the pool.",
    mnDesc:
      "Fauzet mining is a simulation inside the ecosystem — no real Proof-of-Work runs on your device. Buy and upgrade virtual miners, manage energy and efficiency, and earn a share of a limited daily ZYXE pool.",
    mnFormula: "TRANSPARENT REWARD FORMULA",
    mnFormulaText:
      "your valid hashpower ÷ total network hashpower × daily mining pool",
    mnRoom: "MINING ROOM · VISUAL DEMO",
    mnActive: "Illustrative data",
    mnPool: "Daily pool",
    mnShare: "Your share",
    mnEff: "Efficiency",
    mnEst: "Est. today",
    gmTitle: "Games hub",
    gmSub:
      "Two games are available in beta; the remaining cards are clearly marked previews.",
    gmPlay: "Play",
    gmSoon: "Coming soon",
    rfTitle: "Build your Mining Crew",
    rfDesc:
      "Invite friends and earn a share of the rewards generated by your crew’s valid activity — across four levels. Nobody earns for registrations alone.",
    rfLegal:
      "Crew rewards are based on valid platform activity and may be subject to verification, limits and anti-fraud controls. Percentages are configurable and no income is guaranteed.",
    rfConfigNote:
      "Percentages shown are initial values and may change. Rewards apply only to valid, eligible activity.",
    vtTitle: "Vault concept: lock ZYXEs and share a pool.",
    vtDesc:
      "This planned module would let users lock Zyxes for a period and receive a variable pool share weighted by duration. It is not active.",
    vtMultNote: "pool weight multiplier",
    vtLegal:
      "PLANNED FEATURE: no Vault position, multiplier or reward shown here is currently available or guaranteed.",
    cvTag: "CONVERT & WITHDRAW",
    cvTitle: "Convert eligible ZYXEs",
    cvDesc:
      "If this feature is approved and enabled, eligible rewards may be converted into supported assets under limits, fees, KYC and country rules.",
    cvCardTitle: "PLANNED ASSETS",
    cvStatusNotice:
      "Real conversions and withdrawals are not active during the closed beta.",
    tsTitle: "Built on trust",
    tsSub:
      "Security and transparency are part of the product, not an afterthought.",
    finalTitle: "Ready to start earning?",
    finalSub: "Create your free account and enter the closed beta.",
    ftAbout:
      "Fauzet is a gamified micro-rewards platform. Claim, play and mine virtually; real conversion remains planned.",
    ftLegal: "LEGAL",
    ftTerms: "Terms",
    ftPrivacy: "Privacy",
    ftRisk: "Risk notice",
    ftRewardPolicy: "Reward policy",
    ftWithdrawPolicy: "Withdrawal policy",
    ftPlatform: "PLATFORM",
    ftSupport: "SUPPORT",
    ftContact: "Contact",
    ftStatus: "Status",
    ftRights: "All rights reserved.",
    ftDisclaimer:
      "Risk notice: ZYXE is an internal utility and reward unit, not an investment. Rewards are variable and depend on valid activity, available pools and anti-fraud verification. Vault is a planned feature. Trading and conversion are simulated; real crypto withdrawals are disabled.",
  },
  es: {
    navHow: "Cómo funciona",
    navGames: "Juegos",
    navMining: "Minería",
    navRewards: "Recompensas",
    login: "Iniciar sesión",
    getStarted: "Comenzar",
    heroA: "Gana Zyxes.",
    heroB: "Juega, reclama y crece.",
    heroSub:
      "Reclama recompensas internas, juega minijuegos, construye poder de minería virtual y explora el flujo de conversión planificado.",
    ctaStart: "Empieza a ganar",
    ctaExplore: "Explora Fauzet",
    heroDisclaimer:
      "ZYXE es una unidad interna de utilidad y recompensa. Las recompensas son variables, se basan en actividad válida y pueden estar sujetas a verificación, límites y controles antifraude.",
    preview: "Vista previa del producto",
    pvClaim: "Reclamar ZYXEs",
    pvWallet: "Saldo de billetera",
    pvReady: "¡Listo!",
    pvNextClaim: "Próximo reclamo en",
    pvMiningPower: "Poder de minería",
    pvActiveMiners: "Mineros activos",
    pvEfficiency: "Eficiencia",
    pvPoolShare: "Pool diario",
    pvViewDetails: "Ver detalles",
    howTitle: "Cómo funciona Fauzet",
    howSub: "Cuatro pasos desde cero hasta recompensas elegibles.",
    earnTitle: "Formas de ganar",
    earnSub:
      "Acumula ZYXEs con múltiples actividades. Cada recompensa se valida antes de liquidarse.",
    zxTag: "UNIDAD INTERNA DE UTILIDAD",
    zxTitle: "¿Qué puedes hacer con tus ZYXEs?",
    zxDesc:
      "ZYXE es la unidad de recompensa y utilidad del ecosistema Fauzet. Gánala con actividad validada y úsala dentro de la plataforma para crecer más rápido.",
    zxLegal:
      "ZYXE inicia como unidad interna sin precio público ni convertibilidad automática. No representa acciones, deuda ni promesa de rentabilidad.",
    mnTag: "MINERÍA VIRTUAL",
    mnTitle: "Construye poder de minería. Comparte el pool.",
    mnDesc:
      "La minería en Fauzet es una simulación dentro del ecosistema — no se ejecuta Proof-of-Work real en tu dispositivo. Compra y mejora mineros virtuales, gestiona energía y eficiencia, y gana una parte de un pool diario limitado de ZYXE.",
    mnFormula: "FÓRMULA TRANSPARENTE",
    mnFormulaText:
      "tu hashpower válido ÷ hashpower total de la red × pool diario de minería",
    mnRoom: "SALA DE MINERÍA · DEMO VISUAL",
    mnActive: "Datos ilustrativos",
    mnPool: "Pool diario",
    mnShare: "Tu parte",
    mnEff: "Eficiencia",
    mnEst: "Est. hoy",
    gmTitle: "Centro de juegos",
    gmSub:
      "Dos juegos están disponibles en beta; las demás tarjetas son vistas previas claramente marcadas.",
    gmPlay: "Jugar",
    gmSoon: "Próximamente",
    rfTitle: "Construye tu Mining Crew",
    rfDesc:
      "Invita amigos y gana una parte de las recompensas generadas por la actividad válida de tu crew — en cuatro niveles. Nadie gana solo por registros.",
    rfLegal:
      "Las recompensas de crew se basan en actividad válida y pueden estar sujetas a verificación, límites y controles antifraude. Los porcentajes son configurables y no se garantizan ingresos.",
    rfConfigNote:
      "Los porcentajes mostrados son valores iniciales y pueden cambiar. Solo aplica actividad válida y elegible.",
    vtTitle: "Concepto Vault: bloquea ZYXEs y comparte un pool.",
    vtDesc:
      "Este módulo planificado permitiría bloquear Zyxes por un periodo y recibir una parte variable del pool ponderada por duración. No está activo.",
    vtMultNote: "multiplicador de peso",
    vtLegal:
      "FUNCIÓN PLANIFICADA: ninguna posición, multiplicador o recompensa del Vault mostrada aquí está disponible o garantizada.",
    cvTag: "CONVERTIR Y RETIRAR",
    cvTitle: "Convierte ZYXEs elegibles",
    cvDesc:
      "Si esta función se aprueba y habilita, las recompensas elegibles podrán convertirse bajo límites, comisiones, KYC y reglas por país.",
    cvCardTitle: "ACTIVOS PLANIFICADOS",
    cvStatusNotice:
      "Las conversiones y retiros reales no están activos durante la beta cerrada.",
    tsTitle: "Construido sobre confianza",
    tsSub:
      "La seguridad y la transparencia son parte del producto, no una ocurrencia tardía.",
    finalTitle: "¿Listo para empezar a ganar?",
    finalSub: "Crea tu cuenta gratis y entra a la beta cerrada.",
    ftAbout:
      "Fauzet es una plataforma gamificada de micro-recompensas. Reclama, juega y mina virtualmente; la conversión real sigue planificada.",
    ftLegal: "LEGAL",
    ftTerms: "Términos",
    ftPrivacy: "Privacidad",
    ftRisk: "Aviso de riesgo",
    ftRewardPolicy: "Política de recompensas",
    ftWithdrawPolicy: "Política de retiros",
    ftPlatform: "PLATAFORMA",
    ftSupport: "SOPORTE",
    ftContact: "Contacto",
    ftStatus: "Estado",
    ftRights: "Todos los derechos reservados.",
    ftDisclaimer:
      "Aviso de riesgo: ZYXE es una unidad interna de utilidad y recompensa, no una inversión. Las recompensas dependen de actividad válida, pools y controles antifraude. Vault es una función planificada. Trading y conversión son simulados; los retiros cripto reales están deshabilitados.",
  },
} as const;

export function landingData(language: LandingLanguage) {
  const es = language === "es";

  return {
    howSteps: es
      ? [
          [
            "01",
            "Crea tu cuenta",
            "Regístrate con tu email, verifica y protege tu cuenta en minutos.",
          ],
          [
            "02",
            "Reclama y juega",
            "Usa el faucet, juega minijuegos y completa misiones diarias.",
          ],
          [
            "03",
            "Gana y usa Zyxes",
            "Mejora mineros, compra boosts y participa en la economía interna.",
          ],
          [
            "04",
            "Convierte lo elegible",
            "Convierte recompensas validadas cuando esta función esté habilitada.",
          ],
        ]
      : [
          [
            "01",
            "Create your account",
            "Sign up with your email, verify and secure your account in minutes.",
          ],
          [
            "02",
            "Claim and play",
            "Use the faucet, play simple games and complete daily missions.",
          ],
          [
            "03",
            "Earn and use Zyxes",
            "Upgrade miners, buy boosts and take part in the internal economy.",
          ],
          [
            "04",
            "Convert eligible rewards",
            "Convert validated rewards when this feature becomes available.",
          ],
        ],
    earnMethods: es
      ? [
          [
            "ic-faucet.png",
            "Faucet",
            "Reclamos periódicos con cooldown, rachas y multiplicadores.",
          ],
          [
            "ic-games.png",
            "Juegos",
            "Minijuegos cortos con recompensas validadas en servidor.",
          ],
          [
            "ic-mining.png",
            "Minería virtual",
            "Comparte un pool diario según tu hashpower válido.",
          ],
          [
            "ic-missions.png",
            "Misiones",
            "Retos diarios y semanales con progreso claro.",
          ],
          [
            "ic-crew.png",
            "Mining Crew",
            "Comisiones por actividad válida de tu red.",
          ],
          [
            "ic-events.png",
            "Eventos",
            "Próximamente: rankings, torneos y temporadas con pools limitados.",
          ],
          [
            "ic-ads.png",
            "Actividades recompensadas",
            "Próximamente: ofertas voluntarias verificadas por el proveedor.",
          ],
        ]
      : [
          [
            "ic-faucet.png",
            "Faucet",
            "Periodic claims with cooldowns, streaks and multipliers.",
          ],
          [
            "ic-games.png",
            "Games",
            "Short skill games with server-validated rewards.",
          ],
          [
            "ic-mining.png",
            "Virtual mining",
            "Share a limited daily pool based on valid hashpower.",
          ],
          [
            "ic-missions.png",
            "Missions",
            "Daily and weekly challenges with clear progress.",
          ],
          [
            "ic-crew.png",
            "Referral crew",
            "Rewards from your crew’s valid activity.",
          ],
          [
            "ic-events.png",
            "Events",
            "Coming soon: rankings, tournaments and seasons with limited pools.",
          ],
          [
            "ic-ads.png",
            "Rewarded activities",
            "Coming soon: voluntary offers verified by the provider.",
          ],
        ],
    zyxeUses: es
      ? [
          "Comprar boosts",
          "Comprar aceleradores",
          "Mejorar mineros",
          "Restaurar energía",
          "Entrar a eventos",
          "Misiones premium",
          "Vault planificado",
          "Economía interna",
        ]
      : [
          "Buy boosts",
          "Buy accelerators",
          "Upgrade miners",
          "Restore energy",
          "Enter special events",
          "Premium missions",
          "Planned Vault",
          "Internal economy",
        ],
    miners: [
      ["🖥️", "Drip Node", "24 GH/s"],
      ["⚙️", "Core Rig", "46 GH/s"],
      ["🔮", "Nova Rig", "58 GH/s"],
    ],
    games: es
      ? [
          [
            "game-tap.png",
            "Tap Miner",
            "FÁCIL",
            "Toca al ritmo y acumula puntos antes de que acabe el tiempo.",
            "5 energía",
            "5–25 ZYXE",
          ],
          [
            "game-memory.png",
            "Memory Drops",
            "MEDIO",
            "Encuentra los pares. Bonus por tiempo y precisión.",
            "8 energía",
            "10–40 ZYXE",
          ],
          [
            "game-runner.png",
            "Hash Runner",
            "MEDIO",
            "Esquiva obstáculos y multiplica tu puntuación.",
            "10 energía",
            "10–50 ZYXE",
          ],
          [
            "game-faucet.png",
            "Faucet Rush",
            "FÁCIL",
            "Recoge gotas a contrarreloj y mantén tu racha.",
            "5 energía",
            "5–30 ZYXE",
          ],
        ]
      : [
          [
            "game-tap.png",
            "Tap Miner",
            "EASY",
            "Tap to the rhythm and stack points before time runs out.",
            "5 energy",
            "5–25 ZYXE",
          ],
          [
            "game-memory.png",
            "Memory Drops",
            "MEDIUM",
            "Match the pairs. Time and accuracy bonuses.",
            "8 energy",
            "10–40 ZYXE",
          ],
          [
            "game-runner.png",
            "Hash Runner",
            "MEDIUM",
            "Dodge obstacles and multiply your score.",
            "10 energy",
            "10–50 ZYXE",
          ],
          [
            "game-faucet.png",
            "Faucet Rush",
            "EASY",
            "Collect drops against the clock and keep your streak.",
            "5 energy",
            "5–30 ZYXE",
          ],
        ],
    referrals: es
      ? [
          [
            "lvl-1.png",
            "5%",
            "Invitados directos",
            "Sobre actividad válida y monetizable",
          ],
          [
            "lvl-2.png",
            "2%",
            "Crew de tu crew",
            "Sobre actividad válida y monetizable",
          ],
          [
            "lvl-3.png",
            "1%",
            "Tercer nivel",
            "Sobre actividad válida y monetizable",
          ],
          [
            "lvl-4.png",
            "0.5%",
            "Cuarto nivel",
            "Sobre actividad válida y monetizable",
          ],
        ]
      : [
          [
            "lvl-1.png",
            "5%",
            "Direct invites",
            "On valid, monetizable activity",
          ],
          [
            "lvl-2.png",
            "2%",
            "Your crew’s crew",
            "On valid, monetizable activity",
          ],
          ["lvl-3.png", "1%", "Third level", "On valid, monetizable activity"],
          [
            "lvl-4.png",
            "0.5%",
            "Fourth level",
            "On valid, monetizable activity",
          ],
        ],
    vaults: es
      ? [
          ["Flexible", "Disponibilidad inmediata", "1.00×"],
          ["7 días", "Bloqueo corto", "1.05×"],
          ["30 días", "Compromiso medio", "1.15×"],
          ["90 días", "Mayor peso en el pool", "1.35×"],
        ]
      : [
          ["Flexible", "Unlock anytime", "1.00×"],
          ["7 days", "Short lock", "1.05×"],
          ["30 days", "Medium commitment", "1.15×"],
          ["90 days", "Highest pool weight", "1.35×"],
        ],
    conversionPoints: es
      ? [
          "Solo los ZYXEs elegibles y validados pueden convertirse.",
          "Mínimos, fee de red y comisión visibles antes de confirmar.",
          "Revisión de seguridad y antifraude en cada retiro.",
          "Estado blockchain con txid verificable cuando se habilite.",
        ]
      : [
          "Only eligible, validated ZYXEs can be converted.",
          "Minimums, network and service fees shown before confirmation.",
          "Security and anti-fraud review on every withdrawal.",
          "Blockchain status with a verifiable txid once enabled.",
        ],
    assets: [
      ["coin-ltc.png", "Litecoin", es ? "Planificado" : "Planned"],
      ["coin-doge.png", "Dogecoin", es ? "Planificado" : "Planned"],
      ["coin-bch.png", "Bitcoin Cash", es ? "Más adelante" : "Later"],
      ["coin-dash.png", "Dash", es ? "Más adelante" : "Later"],
      ["coin-btc.png", "Bitcoin", es ? "Más adelante" : "Later"],
    ],
    trust: es
      ? [
          [
            "trust-2fa.png",
            "Autenticación 2FA (planificada)",
            "Se exigirá cuando se habiliten retiros, cambios de wallet y otras acciones sensibles.",
          ],
          [
            "trust-fraud.png",
            "Monitoreo antifraude",
            "Risk score, detección de multicuentas y validación de actividad.",
          ],
          [
            "trust-whitelist.png",
            "Lista blanca de wallets (planificada)",
            "Cuando se habiliten los retiros, solo se aceptarán direcciones confirmadas y con cooldown.",
          ],
          [
            "trust-review.png",
            "Revisión de retiros (planificada)",
            "Se aplicarán validaciones automáticas y revisión manual cuando los retiros estén disponibles.",
          ],
          [
            "trust-history.png",
            "Historial completo",
            "Cada movimiento de saldo queda registrado y trazable.",
          ],
          [
            "trust-alert.png",
            "Protección de cuenta",
            "Alertas, gestión de dispositivos y congelación de emergencia.",
          ],
        ]
      : [
          [
            "trust-2fa.png",
            "Two-factor authentication (planned)",
            "It will be required once withdrawals, wallet changes and other sensitive actions are enabled.",
          ],
          [
            "trust-fraud.png",
            "Anti-fraud monitoring",
            "Risk scoring, multi-account detection and activity validation.",
          ],
          [
            "trust-whitelist.png",
            "Wallet whitelist (planned)",
            "Once withdrawals are enabled, only confirmed addresses with a security cooldown will be accepted.",
          ],
          [
            "trust-review.png",
            "Withdrawal review (planned)",
            "Automated checks and manual review will apply once withdrawals become available.",
          ],
          [
            "trust-history.png",
            "Full transaction history",
            "Every balance change is recorded and traceable.",
          ],
          [
            "trust-alert.png",
            "Account protection",
            "Security alerts, device management and emergency freeze.",
          ],
        ],
    faqs: es
      ? [
          [
            "¿Qué es ZYXE?",
            "ZYXE es la unidad interna de recompensa y utilidad de Fauzet. En esta etapa no tiene precio público ni convertibilidad automática y no representa una inversión.",
          ],
          [
            "¿La minería es real?",
            "No. Es una simulación económica y de juego. No ejecutamos minería Proof-of-Work en tu dispositivo.",
          ],
          [
            "¿Puedo retirar mis ZYXEs?",
            "Los retiros reales todavía están deshabilitados. Cuando se habiliten, solo el saldo elegible podrá convertirse, sujeto a mínimos, límites, fees y revisión.",
          ],
          [
            "¿Cómo funciona el Vault?",
            "Repartirá un pool variable según monto y plazo. No existe interés garantizado ni APY fijo.",
          ],
          [
            "¿Cómo gana mi Mining Crew?",
            "Con un porcentaje de actividad válida y monetizable de tu red. No se paga por registros ni depósitos.",
          ],
          [
            "¿El trading es un exchange real?",
            "No. El módulo es simulado o controlado por tesorería; no es un exchange público.",
          ],
          [
            "¿Está disponible en mi país?",
            "La disponibilidad dependerá del país y de la regulación local; las funciones con valor externo usarán una lista de países permitidos.",
          ],
        ]
      : [
          [
            "What is ZYXE?",
            "ZYXE is Fauzet’s internal reward and utility unit. It currently has no public price or automatic convertibility and is not an investment.",
          ],
          [
            "Is the mining real?",
            "No. It is an economic and game simulation. No Proof-of-Work runs on your device.",
          ],
          [
            "Can I withdraw my ZYXEs?",
            "Real withdrawals are currently disabled. Once enabled, only eligible balances may convert, subject to minimums, limits, fees and review.",
          ],
          [
            "How does the Vault work?",
            "It will distribute a variable pool based on amount and lock period. There is no guaranteed interest or fixed APY.",
          ],
          [
            "How does my Mining Crew earn?",
            "Through a percentage of valid, monetizable network activity. Registrations and deposits alone do not earn rewards.",
          ],
          [
            "Is trading a real exchange?",
            "No. The module is simulated or treasury-controlled and is not a public exchange.",
          ],
          [
            "Is Fauzet available in my country?",
            "Availability depends on local rules; features with external value will use a country allowlist.",
          ],
        ],
  } as const;
}
